### ISSUE TITLE
Release UI Redux TODO

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#1384]
Just a place to track progress on introducing Redux in release UI JS.

### TODO

- [ ] migrate other components/state ...
  - [x] `pendingCloses`
  - [ ] `isLoading`
  - [ ] `error`
  - [x] `tracks`
  - [x] `archs`
  - [x] `currentTrack`
- [ ] prepare initial state outside of ReleaseController component
- [ ] use `reselect` or similar for memoized selectors
- [ ] add `enzyme` for component testing
- [ ] add tests of UI components
- [x] move fetching of API responses to actions
- [ ] clean up state to only keep revisions data in one place (`revisions` state), not in channel map
- [ ] split large components into smaller ones with as little logic as possible (just render function with props)

### DONE
- [x] adds Redux and related dependencies (#1375)
- [x] make babel/eslint compile object spread operator { ...state } to make reducers nice (#1375)
- [x] move revisions list data from components into Redux state (#1375)
- [x] move actions to separate modules (#1386)
- [x] test actions and reducers (#1386)
- [x] create selectors for data used by ReleaseList component (#1404)
- [x] test selectors (#1404)
- [x] move all actions from ReleaseList component to redux actions (#1404)
- [x] move all the state from ReleaseList component to redux
  - [x] `revisionsMap` (#1375)
  - [x] `revisionsFilters` (#1393)
  - [x] `releases` (#1393)
  - [x] `selectedRevisions` (#1404)
  - [x] `pendingReleases` (#1412)
  - [x] `releasedChannels` (#1404)
