### ISSUE TITLE
[Vanilla] Public snapcraft pages (IoT, publisher pages etc.)

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2131]
### TODO:
- [x] ALL: navigation hover text color is too dark
- [x] HOME PAGE: clicking on first snap flow language links doesn't scroll panel into view properly
- [x] IOT: cards should use `p-card--highlighted` style
- [x] SEARCH: use `row` instead of `u-fixed-width`
- [ ] DISTRO: there is no space between last paragraph and heading in install instructions card (https://github.com/canonical-web-and-design/vanilla-framework/issues/2447)
- [x] DISTRO: featured snaps are misaligned
