### ISSUE TITLE
Show some information about launchpad builder status on builds tab

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2744]
It would be nice to show some information, or at least a notification that builds may take a while, based on https://launchpad.net/builders.

## Todo:

- [x] Is there an API for that information?
 - Yes: https://api.launchpad.net/devel/builders?ws.op=getBuildQueueSizes
- [x] what is the criteria for notifying builds are currently "slow"
 - Not required: The above API provides an estimate
- [ ] how should the data be displayed - a status indicator? An estimated queue time?
